version: '3.8'

services:
  database:
    container_name: orders-database-dev-ctnr
    image: infuse/orders-database-dev:latest
    build:
      context: .
      dockerfile: ./infra/docker/database/Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
    env_file:
      - ./infra/docker/database/.database.env
    ports:
      - 3306:3306
    volumes:
      - orders_db_data:/var/lib/mysql
    networks:
      - orders-network-dev

  webservice:
    container_name: orders-webservice-dev-ctnr
    image: infuse/orders-webservice-dev:latest
    build:
      context: .
      dockerfile: ./infra/docker/webservice/Dockerfile
    env_file:
      - ./infra/docker/webservice/.webservice.env
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - orders-network-dev

  phpmyadmin:
    container_name: orders-phpmyadmin-dev-ctnr
    image: phpmyadmin:5.2.1
    env_file:
      - ./infra/docker/database/.phpmyadmin.env
    volumes:
      - orders_phpmyadmin_data:/config
    ports:
      - 8090:80
    depends_on:
      - database
    networks:
      - orders-network-dev

volumes:
  orders_db_data:
  orders_phpmyadmin_data:

networks:
  orders-network-dev:
    driver: bridge
