name: WS Pedidos CI

on:
  push:
    branches:
      - "feature/*"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    name: Node.js LTS v20 ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'maven'
      - name: Executa build do JAR
        run: mvn --batch-mode --update-snapshots package -Dmaven.test.skip -DskipTests
      - name: Executa testes unitários
        run: mvn test
