name: WS Pedidos CI

on:
  push:
    branches:
      - "feature/*"
      - "bugfix/*"
      - "refactor/*"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Instalando JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build do projeto
        run: mvn --batch-mode --update-snapshots package -Dmaven.test.skip -DskipTests
      - name: Testes unitários
        run: mvn test
